#!/bin/bash

#A script to install my favorite programs and uninstall programs that I do not want on Fedora

# Enable RPM fusion free, nonfree along with flatpak

sudo dnf install \
  https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm -yy

sudo dnf install \
  https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -yy
  
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

#Update
sudo dnf update -yy

#Remove Programs

echo "*************PURGING PROGRAMS*************"

sudo dnf remove libreoffice* -yy

sudo dnf remove firefox -yy

flatpak install flathub org.mozilla.firefox -yy


#Install Programs

echo "*************INSTALLING PROGRAMS*************"

# No need to install MS fonts. Comes with OnlyOffice.
# sudo dnf install ttf-mscorefonts-installer -yy

sudo dnf install htop -yy

sudo dnf install simplescreenrecorder -yy

sudo dnf install numlockx -yy

sudo dnf install mc -yy

sudo dnf install stacer -yy

sudo dnf install gparted -yy

sudo dnf install brasero -yy

sudo dnf install grub-customizer -yy

#Install Brave Browser

sudo dnf install dnf-plugins-core

sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/

sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

sudo dnf install brave-browser -yy

#Remove, and Clean

echo "*************CLEANING*************"

sudo dnf clean all -yy

#Install Flatpak

flatpak install flathub org.onlyoffice.desktopeditors -yy

flatpak install flathub org.gnome.Cheese -yy

flatpak install flathub org.videolan.VLC -yy

flatpak install flathub fr.handbrake.ghb -yy

flatpak install flathub org.kde.kdenlive -yy

flatpak install flathub com.simplenote.Simplenote -yy

flatpak install flathub org.freefilesync.FreeFileSync -yy

flatpak install flathub org.jitsi.jitsi-meet -yy

flatpak install flathub org.signal.Signal -yy

flatpak install flathub org.audacityteam.Audacity -yy

flatpak install flathub org.videolan.VLC -yy

flatpak install flathub org.gnome.EasyTAG -yy

flatpak install flathub com.spotify.Client -yy

flatpak install flathub org.gtkhash.gtkhash -yy

flatpak install flathub org.mozilla.Thunderbird -yy

flatpak install flathub io.gitlab.librewolf-community -yy

flatpak install flathub org.js.nuclear.Nuclear -yy

flatpak install flathub org.gnome.Boxes -yy

flatpak install flathub org.flameshot.Flameshot -yy

flatpak install flathub com.obsproject.Studio -yy

flatpak install flathub org.gnome.Shotwell -yy

flatpak install flathub life.bolls.bolls -yy
